# Generated by Django 4.2.11 on 2024-04-27 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceprofile',
            old_name='category',
            new_name='categories',
        ),
        migrations.AlterField(
            model_name='serviceprofilecategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_service_profiles', to='services.category'),
        ),
        migrations.AlterField(
            model_name='serviceprofilecategory',
            name='service_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_categories', to='services.serviceprofile'),
        ),
    ]
