# Generated by Django 4.2.11 on 2024-04-30 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_favorite_options_alter_image_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ['service_profile'], 'verbose_name': 'Favorite', 'verbose_name_plural': 'Favorites'},
        ),
        migrations.RemoveConstraint(
            model_name='favorite',
            name='unique_favorite',
        ),
        migrations.RenameField(
            model_name='favorite',
            old_name='service',
            new_name='service_profile',
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('client', 'service_profile'), name='unique_favorite'),
        ),
    ]
