# Generated by Django 4.2.11 on 2024-05-15 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_remove_service_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='serviceprofile',
            name='last_name',
        ),
        migrations.AddField(
            model_name='serviceprofile',
            name='owner_first_name',
            field=models.CharField(default='master1', max_length=128, verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceprofile',
            name='owner_last_name',
            field=models.CharField(default='master1', max_length=128, verbose_name='Фамилия'),
            preserve_default=False,
        ),
    ]
