# Generated by Django 4.2.11 on 2024-04-23 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_remove_service_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='name',
            field=models.CharField(default=1, max_length=256, verbose_name='Наименование услуги'),
            preserve_default=False,
        ),
    ]
