# Generated by Django 4.2.11 on 2024-04-30 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_favorite_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprofile',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата регистрации в приложении'),
        ),
        migrations.AlterField(
            model_name='serviceprofile',
            name='social_network_contacts',
            field=models.URLField(blank=True, max_length=100, null=True, verbose_name='Ссылка на аккаунт в социальных сетях'),
        ),
    ]
