# Generated by Django 4.2.11 on 2024-04-30 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(default=1, max_length=64, verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(default=1, max_length=64, verbose_name='Фамилия'),
            preserve_default=False,
        ),
    ]
